services:
  - type: web
    name: ai-mental-health-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Chatbot.py --server.port $PORT